version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/api-automation-time-tracker

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Build
          command: mvn clean package
      - run:
         name: Test running
         command: mvn test
      - run:
         name: Generate allure report
         command: mvn allure:report
      - store_artifacts:
         path: target/site/allure-maven-plugin
         destination: Allure

workflows:
  version: 2

  commit-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master

  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 3 * * 1,4"
          filters:
            branches:
              only:
                - master
    jobs:
      - schedule_run